# This is yaml for wifi product
router:
  # pls write down the router name .We can use asusac88u and ...
  name: asusax86u

# test list config , such as if you wanna test base function use "wifi_base" , or use "wifi" test rvr
test_config:
  config: wifi_full

rf_solution:
  #  support RC4DAT-8G-95 ,RADIORACK-4-220
  model: RADIORACK-4-220
  RC4DAT-8G-95:
    idVendor: 0x20ce
    idProduct: 0x0023
  RADIORACK-4-220:
    ip_address: 192.168.50.100
  # reduction step for rf signal, can be configured according to test requirements
  step: [ 0 ]

corner_angle:
  # angle step for corner, can be configured according to test requirements
  ip_address: 192.168.50.200
  step: [ 30 ,120 ]
env_command: [ "pwd" ]
#env_command: [ "iwpriv wlan0 set_rate_ofdm 9","iwpriv wlan0 set_rate_ofdm 8","iwpriv wlan0 set_rate_ofdm 3" ]
test_wifi:
  ssid: i-test
  passwd: "@12345678"

pair_num:
  ax:
    '2': { 'tx': [ 10,8,6,4 ],'rx': [ 10,8,6,4 ] }
    '5': { 'tx': [ 15,13,11,9 ],'rx': [ 15,13,11,9 ] }
  ac:
    '5': { 'tx': [ 15,13,11,9 ],'rx': [ 15,13,11,9 ] }
  n:
    '2': { 'tx': [ 10,8,6 ],'rx': [ 10,8,6 ] }
    '5': { 'tx': [ 10,8,6 ],'rx': [ 10,8,6 ] }

# wifi func 004 repeat times
times_004: 3

# wifi func 063 repeat times
times_063: 20

# wifi func 081 repeat times
times_081: 20
accompanying_dut: AMLS905X4AH212BT0318