# config for Android S Certification test
android_s:
  wifi:
    cts_wifi_ssid: "AUT_XTS_5G-1"
    cts_wifi_pwd: "XTS12345678"
    tvts_wifi_ssid: "openwrt_5g"
    tvts_wifi_pwd: "1234567890"
    public_wifi_ssid: "AUT_XTS_5G-2"
    public_wifi_pwd: "XTS12345678"
  google_account:
    cts_username: "amltest9@amlogic.com"
    cts_password: "Qatest123!"
    public_username: "yu.zeng@amlogic.com"
    public_password: "Owen@200714"
  devices:
    cts:
      - device_id: "cts000000031"
        powerRelay: "/dev/powerRelay31"
      - device_id: "cts000000032"
        powerRelay: "/dev/powerRelay32"
      - device_id: "cts000000033"
        powerRelay: "/dev/powerRelay33"
      - device_id: "cts000000034"
        powerRelay: "/dev/powerRelay34"
      - device_id: "cts000000035"
        powerRelay: "/dev/powerRelay35"
      - device_id: "cts000000036"
        powerRelay: "/dev/powerRelay36"
    tvts:
      - device_id: "tvts00000000"
        powerRelay: "/dev/powerRelay_for_tvts"
      - device_id: "tvts00000001"
        powerRelay: "/dev/powerRelay_for_tvts1"
      - device_id: "tvts00000002"
        powerRelay: "/dev/powerRelay_for_tvts2"
      - device_id: "tvts00000003"
        powerRelay: "/dev/powerRelay_for_tvts3"
    gts:
      - device_id: "gts000000001"
        powerRelay: "/dev/powerRelay_for_gts"
    vts:
      - device_id: "vts000000001"
        powerRelay: "/dev/powerRelay_for_vts"
    sts:
      - device_id: "sts000000001"
        powerRelay: "/dev/powerRelay_for_sts"
    cts_single:
      device_id: "cts000000036"
      powerRelay: "/dev/powerRelay36"
    tvts_single:
      device_id: "tvts00000000"
      powerRelay: "/dev/powerRelay_for_tvts"
  chip: "S905X4"
  bluetooth_powerRelay_two:
    - "/dev/powerRelay_for_bluetooth1"
    - "/dev/powerRelay_for_bluetooth2"
  bluetooth_powerRelay_one: "/dev/powerRelay_for_bluetooth3"
  retry_count:
    cts:
      first_loop: 3
      second_loop: 4
      third_loop: 4
    gts:
      first_loop: 3
      second_loop: 4
    tvts:
      first_loop: 5
    sts:
      first_loop: 3
    vts:
      first_loop: 3
  server:
    ip: "127.0.0.1"
    port: 22
    username: "amlogic"
    password: "Linux2017"
  test_suite_path:
    cts: "/home/amlogic/Desktop/android-cts"
    gts: "/home/amlogic/Desktop/android-gts"
    vts: "/home/amlogic/Desktop/android-vts"
    sts: "/home/amlogic/Desktop/android-sts"
    tvts: "/home/amlogic/Desktop/android-tvts"

# config for Android U SH Certification test
android_u_sh:
  wifi:
    cts_wifi_ssid: "AUT_XTS_5G-1"
    cts_wifi_pwd: "XTS12345678"
    tvts_wifi_ssid: "openwrt_5g"
    tvts_wifi_pwd: "1234567890"
    public_wifi_ssid: "AUT_XTS_5G-2"
    public_wifi_pwd: "XTS12345678"
  google_account:
    cts_username: "amltest9@amlogic.com"
    cts_password: "Qatest123!"
    public_username: "yu.zeng@amlogic.com"
    public_password: "Owen@200714"
  devices:
    cts:
      - device_id: "cts000000031"
        powerRelay: "/dev/powerRelay31"
      - device_id: "cts000000032"
        powerRelay: "/dev/powerRelay32"
      - device_id: "cts000000033"
        powerRelay: "/dev/powerRelay33"
      - device_id: "cts000000034"
        powerRelay: "/dev/powerRelay34"
      - device_id: "cts000000035"
        powerRelay: "/dev/powerRelay35"
      - device_id: "cts000000036"
        powerRelay: "/dev/powerRelay36"
      - device_id: "tvts00000003"
        powerRelay: "/dev/powerRelay37"
    tvts:
      - device_id: "tvts00000000"
        powerRelay: "/dev/powerRelay_for_tvts"
      - device_id: "tvts00000001"
        powerRelay: "/dev/powerRelay_for_tvts1"
      - device_id: "tvts00000002"
        powerRelay: "/dev/powerRelay_for_tvts2"
#      - device_id: "tvts00000003"
#        powerRelay: "/dev/powerRelay_for_tvts3"
    gts:
      - device_id: "gts000000001"
        powerRelay: "/dev/powerRelay_for_gts"
    vts:
      - device_id: "vts000000001"
        powerRelay: "/dev/powerRelay_for_vts"
    sts:
      - device_id: "sts000000001"
        powerRelay: "/dev/powerRelay_for_sts"
    cts_single:
      device_id: "cts000000036"
      powerRelay: "/dev/powerRelay36"
    tvts_single:
      device_id: "tvts00000001"
      powerRelay: "/dev/powerRelay_for_tvts"
  chip: "S905X4"
  bluetooth_powerRelay_two:
    - "/dev/powerRelay_for_bluetooth1"
    - "/dev/powerRelay_for_bluetooth2"
  bluetooth_powerRelay_one: "/dev/powerRelay_for_bluetooth3"
  retry_count:
    cts:
      first_loop: 5
      second_loop: 2
    gts:
      first_loop: 4
      second_loop: 2
    tvts:
      first_loop: 5
    sts:
      first_loop: 3
    vts:
      first_loop: 3
  server:
    ip: "127.0.0.1"
    port: 22
    username: "amlogic"
    password: "Linux2017"
  test_suite_path:
    cts: "/home/amlogic/Android_U_Certification/android-cts"
    gts: "/home/amlogic/Android_U_Certification/android-gts"
    vts: "/home/amlogic/Android_U_Certification/android-vts"
    sts: "/home/amlogic/Android_U_Certification/android-sts"
    tvts: "/home/amlogic/Android_U_Certification/android-tvts"
  netflix:
    account: "tester_xts@netflix.com"
    password: "Amlogic123!m"

# config for Android U XA Certification test
android_u_xa:
  wifi:
    cts_wifi_ssid: "galaxy"
    cts_wifi_pwd: "Home1357"
    tvts_wifi_ssid: "openwrt_5g"
    tvts_wifi_pwd: "1234567890"
    public_wifi_ssid: "ASUS_5G"
    public_wifi_pwd: "Home1357"
  google_account:
    cts_username: "yu.zeng@amlogic.com"
    cts_password: "Owen@200714"
    public_username: "yu.zeng@amlogic.com"
    public_password: "Owen@200714"
  devices:
    cts:
      - device_id: "ohmcts001"
        powerRelay: "/dev/powerRelay_for_cts1"
      - device_id: "ohmcts002"
        powerRelay: "/dev/powerRelay_for_cts2"
      - device_id: "ohmcts003"
        powerRelay: "/dev/powerRelay_for_cts3"
      - device_id: "ohmcts004"
        powerRelay: "/dev/powerRelay_for_cts4"
      - device_id: "ohmcts005"
        powerRelay: "/dev/powerRelay_for_cts5"
      - device_id: "ohmcts006"
        powerRelay: "/dev/powerRelay_for_cts6"
    tvts:
      - device_id: "ohmtvts001"
        powerRelay: "/dev/powerRelay_for_tvts1"
      - device_id: "ohmtvts002"
        powerRelay: "/dev/powerRelay_for_tvts2"
    gts:
      - device_id: "ohmgts001"
        powerRelay: "/dev/powerRelay_for_gts"
    vts:
      - device_id: "ohmvts001"
        powerRelay: "/dev/powerRelay_for_vts"
    sts:
      - device_id: "ohmsts001"
        powerRelay: "/dev/powerRelay_for_sts"
    cts_single:
      device_id: "ohmcts001"
      powerRelay: "/dev/powerRelay_for_cts1"
    tvts_single:
      device_id: "ohmtvts002"
      powerRelay: "/dev/powerRelay_for_tvts2"
  chip: "S905X4"
  bluetooth_powerRelay_two:
    - "/dev/powerRelay_for_bluetooth1"
    - "/dev/powerRelay_for_bluetooth2"
  bluetooth_powerRelay_one: "/dev/powerRelay_for_bluetooth3"
  retry_count:
    cts:
      first_loop: 5
      second_loop: 2
    gts:
      first_loop: 4
      second_loop: 2
    tvts:
      first_loop: 5
    sts:
      first_loop: 3
    vts:
      first_loop: 3
  server:
    ip: "127.0.0.1"
    port: 22
    username: "amlogic"
    password: "Linux2017"
  netflix:
    account: "tester_xts@netflix.com"
    password: "Amlogic123!m"
